### ISSUE TITLE
Include folder molecule in linting with ansible-lint and remove linting violations

### ISSUE THREAD

**Issue by christianhueserhzdr** [hifis-net/ansible-role-gitlab#52]
When providing `.` as the folder path of the lintables to `ansible-lint` it does not lint the folder `molecule/default` containing `converge.yml`, `prepare.yml`, `verify.yml`, hence folder `molecule/` need to be added to the `ansible-lint` call in the `molecule lint` commands.

Linting violations need to be fixed alongside this change.

**Comment by tobiashuste** [comment]
Closed via #53
